### ISSUE TITLE
ideas brainstorm

### ISSUE THREAD

**Issue by mkuzak** [simoncodes/simoncodes#1]
example of simon says in html5
http://labs.uxmonk.com/simon-says/
https://github.com/dbchristopher/HTML5-Simon-Says
https://www.danpurdy.co.uk/tutorial/simon-says-game-in-jquery-tutorial/

js/html5 game engeines/frameworks:
http://phaser.io/
https://playcanvas.com/
https://github.com/GoodBoyDigital/pixi.js

big framework list:
https://html5gameengine.com/

simon says for tizen-tv example with phaser
http://phaser.io/news/2014/11/2-new-tizen-tv-phaser-examples

simon sez in phaser (simpler example)
http://phaser.io/examples/v2/games/simon

**Comment by drjwbaker** [comment]
Simon Say chosen.
