### ISSUE TITLE
we need some distractions

### ISSUE THREAD

**Issue by tompollard** [simoncodes/simoncodes#2]

**Comment by drjwbaker** [comment]
## Images

Mock [Blue Screen of Death](http://hackspc.com/wp-content/uploads/2010/11/blue-screen-of-death.jpg) (jpg)
[A Gif on Distraction](http://cdn2.hubspot.net/hub/250707/file-2433066421-gif/i-cared-for-8-seconds-and-then-i-got-distracted.gif?t=1427152807435)
[Annoying person gif](http://i.giphy.com/c3pxK8VDwQX1m.gif)

From DPLA's [GIF IT UP](http://dp.la/info/gif-it-up/) (CC0 Public Domain Declaration):
- [Butterly and Flower](http://imgur.com/zZscrLm) http://i.imgur.com/zZscrLm.gif
- [Ski jumping[(http://public.media.smithsonianmag.com//filer/fe/23/fe2367c2-2899-4211-937c-d96ddc8937ff/excellent_wipeouts_circa_1946_-_imgur.gif)
- [Dog Typing](http://imgur.com/tbIq2nD) http://i.imgur.com/tbIq2nD.gif
- [Plane Flying at you](http://i.imgur.com/KBb7408.gif)

## Video

[Vpeeker[(http://www.vpeeker.com/) Pull in random segment of live Vines? (they tend to be annoying...)

## Microgames

Swap [Git](https://github.com/nmoroze/swap) [Game](http://nmoroze.github.io/swap/) _May_ be able to pluck out single levels as a metachallenge during breaks
[PuzzleScript](www.puzzlescript.net/editor.html) Perhaps build a very short game as an interupt...

**Comment by drjwbaker** [comment]
Went for gifs from GIF IT UP (easy to implement).
