### ISSUE TITLE
Gather background info on programming and working environment

### ISSUE THREAD

**Issue by tompollard** [simoncodes/simoncodes#6]
To guide development we should look at background info such as:

: research on programming and distractions
: personal stories/surveys/etc

**Comment by tompollard** [comment]
### StackExchange: "Does anyone have any links to studies that show how noise affects the productivity of programmers?

...While programming I'm usually thinking verbally, and any talking whatsoever destroys my train of thought. I'm literally incapable of programming anywhere where there is audible conversation."

http://programmers.stackexchange.com/questions/132952/studies-on-how-noise-affects-productivity-of-programmers

The answers are fairly vague and suggest little research in this area. There is a reference to a book called Peopleware, which is summarised at: http://javatroopers.com/Peopleware.html

A similar question is posted here: http://programmers.stackexchange.com/questions/56220/is-there-any-scholarly-research-on-the-detrimental-effects-of-a-noisy-workplace

**Comment by tompollard** [comment]
### 2013 IT World article discussing programming environment:

http://www.itworld.com/article/2706181/it-management/here-s-one-way-to-improve-programmers--productivity-that-doesn-t-involve-red-bull.html

"The key, of course, is the type of distraction. Being regularly interrupted with questions, or just by ambient noise that’s too loud, can take a developer (or anybody, for that matter) out of “the flow”. Getting back into that flow can take a significant amount of time. "

Highlights work suggesting that ambient "hum of a coffee shop" can be a positive thing in terms of creativity:
http://www.jstor.org/stable/full/10.1086/665048
http://well.blogs.nytimes.com//2013/06/21/how-the-hum-of-a-coffee-shop-can-boost-creativity/

**Comment by tompollard** [comment]
### Many popular blog articles written by people expressing their feelings

This is a nice one: http://mattrogish.com/blog/2012/03/17/open-plan-offices-must-die/

Includes several references to interesting sources.

Lots of comments from people feeling the same way too. e.g.:

"This is the most common problem I've observed as a software developer in all my years of work. I don't understand why managerial decision makers everywhere have yet to figure this out."

**Comment by tompollard** [comment]
### Research paper on "Coherence of the Irrelevant-Sound Effect: Individual Profiles of Short-term Memory and Susceptibility to Task-Irrelevant Materials"

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2669750/

"The disruptive effects of irrelevant sounds on immediate serial recall are of considerable interest. This disruption is typically referred to as the irrelevant speech effect (Colle & Welsh, 1976; Salamé & Baddeley, 1982) but also the irrelevant sound effect (ISE; Jones & Macken, 1993) given that it can occur with nonspeech sounds.  

Fundamentally, the ISE reflects an important limitation in humans' ability to determine which stimuli will enter into the mnemonic processing needed for short-term recall. To the extent that the ISE affects processes within short-term recall that are also used more widely in cognitive tasks, it is of broad significance. Yet, important questions remain..."

**Comment by tompollard** [comment]
### Article that suggests mentally changing context upsets "flow"

Many of the discussions on programming environment refer to the importance of "flow". e.g.: this article in http://www.devx.com/DevX/Article/11659

"Flow takes time to achieve, and it is fragile. If a programmer's flow is interrupted it can take a large amount of time for her to regain the state, sometimes up to an hour. That's an hour of lost productivity to your team. If a programmer is interrupted many times during the day she may never reach this state. Without this state, creativity is crippled. 

Flow is fragile but, thankfully, it isn't as fragile as it first seems. Flow can only be broken if an interruption requires a programmer to mentally change contexts. This means that you can tap a programmer on the shoulder and ask them what they're doing, or even suggest a line of reasoning to them, and everything will be fine. But if you ask them where their timesheet is, you've broken it."

**Comment by drjwbaker** [comment]
Happy to close this now @tompollard ?

**Comment by tompollard** [comment]
yep!
