### ISSUE TITLE
image on gh-pages is not found

### ISSUE THREAD

**Issue by tompollard** [simoncodes/simoncodes#7]
I can't find the following image:
https://dl-web.dropbox.com/get/root/bl/talks/2015-03_CW15/IMG_20150327_113943.jpg?_subject_uid=7685990&w=AAC1D4OIAYQ8ZSUf7TbXmxNdAdW3LSH0-DLQJj9utafsUA

We should add the image to the repository and link to this instead.

**Comment by drjwbaker** [comment]
Sure thing. I'll give it a go!

**Comment by drjwbaker** [comment]
Fixed http://simoncodes.github.io/simoncodes/images/img1.jpg
